-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.car
(
    code integer NOT NULL,
    brand character varying(100) NOT NULL,
    model character varying(100) NOT NULL,
    year integer NOT NULL,
    category character varying(8) NOT NULL DEFAULT STANDARD,
    fuel character varying(8) NOT NULL,
    seats smallint NOT NULL DEFAULT 4,
    acessories character varying(100)[],
    price_per_day_in_cents integer NOT NULL,
    value integer NOT NULL,
    status character varying(8) NOT NULL,
    cnpj_car_rental_company character(14)[] NOT NULL,
	CONSTRAINT category_check CHECK (category IN ('STANDARD', 'SPORT', 'VAN')),
	CONSTRAINT fuel_check CHECK (fuel IN ('GASOLINE', 'ETHANOL', 'DIESEL', 'FLEX', 'HYBRID')),
	CONSTRAINT status_check CHECK (status IN ('ACTIVE', 'INACTIVE')),
    PRIMARY KEY (code)
);

CREATE TABLE IF NOT EXISTS public.car_rental_company
(
    name character varying(200) NOT NULL,
    street character varying(100) NOT NULL,
    "number" integer NOT NULL,
    district character varying(100) NOT NULL,
    city character varying(100) NOT NULL,
    state character varying(50) NOT NULL,
    zip_code character(8)[],
    cnpj character(14)[] NOT NULL,
    secret_code integer NOT NULL,
    PRIMARY KEY (cnpj, secret_code)
);

CREATE TABLE IF NOT EXISTS public.client
(
    name character varying(100) NOT NULL,
    cpf character(11)[] NOT NULL,
    phone_number character varying(20) NOT NULL,
    email character varying(320) NOT NULL,
    username character varying(50) NOT NULL,
    password character varying(50),
    status character varying(8) NOT NULL,
    street character varying(100) NOT NULL,
    "number" integer NOT NULL,
    district character varying(100) NOT NULL,
    zip_code character(8)[],
	CONSTRAINT status_check CHECK (status IN ('ACTIVE', 'INACTIVE')),
    PRIMARY KEY (cpf, email, username)
);

CREATE TABLE IF NOT EXISTS public.manager
(
    name character varying(100) NOT NULL,
    cpf character(11)[] NOT NULL,
    phone_number character varying(20) NOT NULL,
    email character varying(320) NOT NULL,
    username character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    status character varying(8) NOT NULL,
    car_rental_company_secret_code integer NOT NULL,
	CONSTRAINT status_check CHECK (status IN ('ACTIVE', 'INACTIVE')),
    PRIMARY KEY (cpf, email, username)
);

ALTER TABLE IF EXISTS public.car
    ADD FOREIGN KEY (cnpj_car_rental_company)
    REFERENCES public.car_rental_company (cnpj) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.manager
    ADD FOREIGN KEY (car_rental_company_secret_code)
    REFERENCES public.car_rental_company (secret_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;